title: Jaden Majid
permalink: /blog/posts/:title.html
highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
